from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml

from agents.models import CapabilityGapSpec, GeneratedOperatorDraft, RuleCompilationResult
from agents.prompts import (
    CAPABILITY_EXTENSION_SYSTEM_PROMPT,
    build_capability_gap_user_prompt,
    build_operator_base_interface_text,
)
from agents.providers.base import LLMProvider
from validation.registry import OperatorRegistry, registry as default_registry

GENERATED_DRAFTS_DIR = Path(__file__).resolve().parents[1] / "generated_drafts"


class CapabilityExtensionAgent:
    """Triggered only when the Rule Authoring Agent returns
    UNSUPPORTED_CAPABILITY. Specifies and can draft a reusable operator, but
    NEVER writes anywhere the app imports from, and generated code is never
    auto-executed - see save_draft() and scripts/promote_operator.py.
    """

    def __init__(self, provider: LLMProvider, operator_registry: OperatorRegistry = default_registry) -> None:
        self._provider = provider
        self._registry = operator_registry

    def specify_gap(self, rule_text: str, compilation_result: RuleCompilationResult) -> CapabilityGapSpec:
        if compilation_result.status.value != "UNSUPPORTED_CAPABILITY":
            raise ValueError("specify_gap requires an UNSUPPORTED_CAPABILITY compilation result")
        user_prompt = build_capability_gap_user_prompt(
            rule_text,
            compilation_result.understood_goal or "",
            compilation_result.missing_capabilities,
            self._registry,
        )
        return self._provider.structured_generate(
            CAPABILITY_EXTENSION_SYSTEM_PROMPT, user_prompt, CapabilityGapSpec
        )

    def generate_draft(self, gap_spec: CapabilityGapSpec) -> GeneratedOperatorDraft:
        user_prompt = (
            f"Capability gap spec:\n{gap_spec.model_dump_json(indent=2)}\n\n"
            f"Operator base interface:\n{build_operator_base_interface_text()}\n"
        )
        # Full implementation_code + test_code can easily run past the
        # default 4096-token budget (got truncated mid-response in practice,
        # producing an incomplete tool call) - this one call needs more room.
        return self._provider.structured_generate(
            CAPABILITY_EXTENSION_SYSTEM_PROMPT, user_prompt, GeneratedOperatorDraft, max_tokens=16384
        )


def save_draft(draft: GeneratedOperatorDraft, gap_spec: CapabilityGapSpec, drafts_dir: Path = GENERATED_DRAFTS_DIR) -> Path:
    """Writes the draft ONLY under generated_drafts/<operator_name>/. The
    Streamlit app and validation engine must never import from this
    directory - a developer promotes it explicitly (scripts/promote_operator.py)."""
    target_dir = drafts_dir / draft.operator_name
    target_dir.mkdir(parents=True, exist_ok=True)

    (target_dir / "operator.py").write_text(draft.implementation_code)
    (target_dir / "test_operator.py").write_text(draft.test_code)
    (target_dir / "metadata.yaml").write_text(
        yaml.safe_dump(
            {
                "operator_name": draft.operator_name,
                "generated_at": datetime.utcnow().isoformat(),
                "gap_spec": gap_spec.model_dump(mode="json"),
                "metadata": draft.metadata,
            },
            sort_keys=False,
        )
    )
    (target_dir / "README.md").write_text(
        f"# DRAFT operator: {draft.operator_name}\n\n"
        "Generated by the Capability Extension Agent. NOT imported or executed by the app.\n\n"
        f"## Purpose\n{gap_spec.purpose}\n\n"
        f"## Notes\n{draft.notes or '(none)'}\n\n"
        "## Promotion\n"
        f"```\npython -m scripts.promote_operator generated_drafts/{draft.operator_name}\n```\n"
    )
    return target_dir
